apiVersion: apps/v1
kind: Deployment
metadata:
  name: serv
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serv
  template:
    metadata:
      labels:
        app: serv
    spec:
      containers:
      - name: serv
        image: paulclrt/serv:latest
        ports:
        - containerPort: 5000