apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-load-balancer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-load-balancer
  template:
    metadata:
      labels:
        app: nginx-load-balancer
    spec:
      containers:
      - name: nginx
        image: paulclrt/nginx:latest
        ports:
        - containerPort: 80