apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: default
spec:
  selector:
    app: nginx-load-balancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Change this as needed (e.g., ClusterIP, NodePort)
